CREATE TABLE teams (
        team CHAR(3) NOT NULL,
  	location VARCHAR(20) NOT NULL,
  	name VARCHAR(20),
  	leag CHAR(1) NOT NULL,
  	PRIMARY KEY (team, leag));

CREATE TABLE players (
       ilkid VARCHAR(10) NOT NULL,
       firstname VARCHAR(10) NOT NULL,
       lastname VARCHAR(20) NOT NULL,
       position CHAR(1) NOT NULL,
       firstseason INT NOT NULL,
       lastseason INT NOT NULL,
       h_feet INT NOT NULL,
       h_inches INT NOT NULL,
       weight INT,
       college VARCHAR(30),
       birthdate VARCHAR(16) NOT NULL,
       PRIMARY KEY (ilkid));

CREATE TABLE player_regular_season_career (
        ilkid VARCHAR(10) NOT NULL,
        firstname VARCHAR(10) NOT NULL,
        lastname VARCHAR(20) NOT NULL,
        leag CHAR(1) NOT NULL,
        gp INT,
        minutes INT,
        pts INT,
        oreb INT,
        dreb INT,
        reb INT,
        asts INT,
        stl INT,
        blk INT,
        turnover INT,
        pf INT,
        fga INT,
        fgm INT,
        fta INT,
        ftm INT,
        tpa INT,
        tpm INT,
        PRIMARY KEY (ilkid,pts));

CREATE TABLE player_regular_season (
        ilkid VARCHAR(10) NOT NULL,
        year INT,
        firstname VARCHAR(10) NOT NULL,
        lastname VARCHAR(20) NOT NULL,
        team CHAR(3),
        leag CHAR(1) NOT NULL,
        gp INT,
        minutes INT,
        pts INT,
        oreb INT,
        dreb INT,
        reb INT,
        asts INT,
        stl INT,
        blk INT,
        turnover INT,
        pf INT,
        fga INT,
        fgm INT,
        fta INT,
        ftm INT,
        tpa INT,
        tpm INT,
        PRIMARY KEY (ilkid,year,team));
CREATE TABLE player_playoffs_career (
        ilkid VARCHAR(10) NOT NULL,
        firstname VARCHAR(10) NOT NULL,
        lastname VARCHAR(20) NOT NULL,
        leag CHAR(1) NOT NULL,
        gp INT,
        minutes INT,
        pts INT,
        oreb INT,
        dreb INT,
        reb INT,
        asts INT,
        stl INT,
        blk INT,
        turnover INT,
        pf INT,
        fga INT,
        fgm INT,
        fta INT,
        ftm INT,
        tpa INT,
        tpm INT,
        PRIMARY KEY (ilkid,minutes));
CREATE TABLE player_playoffs (
        ilkid VARCHAR(10) NOT NULL,
        year INT,
        firstname VARCHAR(10) NOT NULL,
        lastname VARCHAR(20) NOT NULL,
        team CHAR(3),
        leag CHAR(1) NOT NULL,
        gp INT,
        minutes INT,
        pts INT,
        oreb INT,
        dreb INT,
        reb INT,
        asts INT,
        stl INT,
        blk INT,
        turnover INT,
        pf INT,
        fga INT,
        fgm INT,
        fta INT,
        ftm INT,
        tpa INT,
        tpm INT,
        PRIMARY KEY (ilkid,year,team));
CREATE TABLE coaches_season (
       coachid VARCHAR(10) NOT NULL,
       year INT,
       yr_order INT,
       firstname VARCHAR(10),
       lastname VARCHAR(15),
       season_win INT,
       season_loss INT,
       playoff_win INT,
       playoff_loss INT,
       team CHAR(3),
       PRIMARY KEY (coachid,year,yr_order));
CREATE TABLE coaches_career (
       coachid VARCHAR(10) NOT NULL,
       firstname VARCHAR(10),
       lastname VARCHAR(15),
       season_win INT,
       season_loss INT,
       playoff_win INT,
       playoff_loss INT,
       PRIMARY KEY (coachid,season_win));


     

       